### ISSUE TITLE
Publish as website

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-stories#7]
We should convert this content into a proper website.  I see two options:

1.  Integrate it into the dask repository and dask documentation
2.  Use a separate site and a static site generator, like Jekyll

**Comment by djhoese** [comment]
Would you be willing to put all of the stories (.md files at least) under a `docs` directory? Then you could just configure the github repository to generate a github.io site (dask.github.io/dask-stores).

**Comment by djhoese** [comment]
Or maybe just the `master` branch: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by mrocklin** [comment]
No objection.  The current sphinx solution at
https://dask-stories.readthedocs.io/en/latest/ is a bit bare bones.  If
someone wanted to do a bit of CSS to make things nicer that would be
welcome, regardless of how things are organized.

**Comment by mrocklin** [comment]
Orthogonally, it would be nice to merge all of the dask-foo.readthecos.io
sites into one domain.  There are some other conversations happening on
this at dask weekly meetings these days

**Comment by kitaev-chen** [comment]
Here is a modern style for scientific story writing (distill), just FYI 
https://distill.pub/2018/differentiable-parameterizations/

**Comment by mrocklin** [comment]
We're live at https://stories.dask.org 

Closing
